# Numpy 
* Numpy is numerical python 

In [4]:
import numpy as np

# Numpy function 

In [8]:
a1 = np.array([[1,2,3],[4,5,6]])

In [9]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a2 = np.zeros((5,6), dtype = int)

In [15]:
a2

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [16]:
a3 = np.arange(2,10,2)

In [17]:
a3

array([2, 4, 6, 8])

In [18]:
a4 = np.ones((3,4) , dtype = int)

In [19]:
a4

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [22]:
a5 = np.linspace(10,30,3)

In [23]:
a5

array([10., 20., 30.])

In [5]:
a6 = np.random.randint(0,15,size=(3,4))

In [6]:
a6

array([[ 2,  2, 12,  1],
       [13,  8,  0, 12],
       [ 4,  2,  6,  7]])

In [9]:
a7 = np.full((2,2,2),4)

In [10]:
a7

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [12]:
a8 = np.identity(4)

In [13]:
a8

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
list = [1,2,3,4,5]
a9 = np.asarray(list)


In [16]:
a9

array([1, 2, 3, 4, 5])

In [17]:
a = (5,10)
b = (5,12)

In [18]:
np.multiply(a,b)

array([ 25, 120])

In [19]:
np.divide(a,b)

array([1.        , 0.83333333])

In [20]:
divide =np.divide(10,5)

In [22]:
divide

2.0

In [24]:
mul =np.multiply(10,5)

In [25]:
mul

50

# aggregation operation 


In [26]:
data = np.random.randint(1,10,(2,4))

In [27]:
data

array([[8, 5, 2, 1],
       [2, 5, 3, 8]])

In [28]:
#sum
print(np.sum(data))
print(np.sum(data,axis=0))
print(np.sum(data,axis=1))

34
[10 10  5  9]
[16 18]


In [29]:
data.max()

8

In [30]:
data.min()

1

# Numpy array attributes 

In [31]:
a1 =np.array([[1,2,3],[4,5,6]])
print(a1.shape)

(2, 3)


In [32]:
a2 = np.array([[1,2,3],[4,5,6]])
print(f"the dimension of a2:",a2.ndim)

the dimension of a2: 2


In [33]:
a3 = np.array([[1,2,3],[4,5,6]])
print(f"elments in a3 = {a3.size}")

elments in a3 = 6


In [35]:
a5 = np.array([1,2,3])
print(a5.dtype)

int32


# Array Manipulation

In [36]:
a6 = np.array(np.random.randint(1,6,(6,3)))
a6

array([[4, 4, 3],
       [2, 2, 5],
       [5, 5, 5],
       [4, 3, 4],
       [5, 2, 3],
       [4, 4, 1]])

In [38]:
transpose_array = np.transpose(a6)

In [39]:
transpose_array

array([[4, 2, 5, 4, 5, 4],
       [4, 2, 5, 3, 2, 4],
       [3, 5, 5, 4, 3, 1]])

In [40]:
a7 = np.array(np.random.randint(1,6,(6,3)))

In [50]:
a7

array([[5, 3, 3],
       [2, 3, 1],
       [1, 5, 5],
       [2, 4, 2],
       [3, 5, 1],
       [3, 1, 5]])

In [51]:
a7 = np.array(np.random.randint(1,6,(6,2)))
a7

array([[3, 5],
       [4, 1],
       [1, 5],
       [3, 2],
       [4, 4],
       [2, 1]])

In [52]:
a7.flatten()

array([3, 5, 4, 1, 1, 5, 3, 2, 4, 4, 2, 1])